name: Release (Next)

on:
  push:
    branches:
      - next

jobs:
  release:

    name: Release (Next)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: volta-cli/action@v1

    - run: npm ci
    
    - run: npx lerna bootstrap --ci

    - name: Create Release Pull Request or Publish to npm
      id: changesets
      uses: changesets/action@master
      with:
        version: npx changeset version
        publish: npx lerna exec --scope microsite -- npm publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
